### ISSUE TITLE
Fix Heroku deploy

### ISSUE THREAD

**Issue by amdelamar** [RamblingWare/Rant#40]
There needs to be a 'stage' build task in gradle.
Also specify JDK 9.
Should also check 'server.port' and not auto-forward to https.

See
https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku

**Comment by amdelamar** [comment]
Getting error
```
2018-06-17T19:59:22.758942+00:00 app[web.1]: SEVERE: Unexpected exception in route
2018-06-17T19:59:22.758945+00:00 app[web.1]: freemarker.template.TemplateNotFoundException: Template not found for name "/app/webroot/templates/index.ftl".
2018-06-17T19:59:22.758946+00:00 app[web.1]: The name was interpreted by this TemplateLoader: io.vertx.ext.web.templ.impl.FreeMarkerTemplateLoader@dfd03bb.
2018-06-17T19:59:22.758948+00:00 app[web.1]: at freemarker.template.Configuration.getTemplate(Configuration.java:2797)
2018-06-17T19:59:22.758950+00:00 app[web.1]: at freemarker.template.Configuration.getTemplate(Configuration.java:2599)
2018-06-17T19:59:22.758952+00:00 app[web.1]: at io.vertx.ext.web.templ.impl.FreeMarkerTemplateEngineImpl.render(FreeMarkerTemplateEngineImpl.java:74)
2018-06-17T19:59:22.758954+00:00 app[web.1]: at io.vertx.reactivex.ext.web.templ.TemplateEngine.render(TemplateEngine.java:116)
2018-06-17T19:59:22.758956+00:00 app[web.1]: at org.oddox.action.BlogAction.handle(BlogAction.java:102)
2018-06-17T19:59:22.758957+00:00 app[web.1]: at org.oddox.action.BlogAction.handle(BlogAction.java:25)
```

But the mentioned file exists:
```
$ heroku run ls -lsa webroot/templates -a app
Running ls -lsa webroot/templates on app... starting, run.5170 (Free)
Running ls -lsa webroot/templates on app... connecting, run.5170 (Free)
Running ls -lsa webroot/templates on app... up, run.5170 (Free)
total 48
4 drwx------ 9 u55354 dyno 4096 Jun 17 19:57 .
4 drwx------ 5 u55354 dyno 4096 Jun 17 19:57 ..
4 -rw------- 1 u55354 dyno  542 Jun 17 19:57 about.ftl
4 drwx------ 2 u55354 dyno 4096 Jun 17 19:57 author
4 drwx------ 2 u55354 dyno 4096 Jun 17 19:57 blog
4 drwx------ 2 u55354 dyno 4096 Jun 17 19:57 category
4 drwx------ 2 u55354 dyno 4096 Jun 17 19:57 error
4 drwx------ 3 u55354 dyno 4096 Jun 17 19:57 fragment
4 -rw------- 1 u55354 dyno  852 Jun 17 19:57 index.ftl
4 -rw------- 1 u55354 dyno  750 Jun 17 19:57 search.ftl
4 drwx------ 2 u55354 dyno 4096 Jun 17 19:57 tag
4 drwx------ 2 u55354 dyno 4096 Jun 17 19:57 year
```

Unsure how to proceed at this point.
